//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADDLBankingApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marchamo
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public string NumberPlate { get; set; }
        public string VehicleType { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
