//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADDLBankingApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateExpiration { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
