//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADDLBankingApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stadistic
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public string Platform { get; set; }
        public string Browser { get; set; }
        public string Page { get; set; }
        public string Action { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
